---

# configure component proportions
proportions:
  height:
    heading: 0.30
    seperator: 0.02
    index_text: 0.18
    index_gap: 0.05
    index_ticks: 0.03
    spectrum: 0.36
    bottom_gap: 0.06
  width:
    gap: 0.07  # x2 for LHS & RHS
    spectrum: 0.86


# configure the background
background:
  colour: [1, 1, 1]
  cmap_name: plasma


# configurate lines
lines:
  border:
    colour: [0, 0, 0]
    type: BORDER_CONSTANT
    width_proportion: 0.008
  seperator:
    colour: [0, 0, 0]
  index:
    colour: [0, 0, 0]
    num: 4
    width_proportion: 0.01


# configure text
text:
  heading:
    colour: [0, 0, 0]
    font_type: FONT_HERSHEY_SIMPLEX
    line_type: 1
    proportions:
      size: 0.002
      thickness: 0.005
  index:
    colour: [0, 0, 0]
    font_type: FONT_HERSHEY_SIMPLEX
    line_type: LINE_AA
    proportions:
      size: 0.0015
      thickness: 0.005
