
import cv2

cv2_dict = {

    "BORDER_REPLICATE": cv2.BORDER_REPLICATE,
    "BORDER_CONSTANT": cv2.BORDER_CONSTANT,

    "FONT_HERSHEY_SIMPLEX": cv2.FONT_HERSHEY_SIMPLEX,
    "FONT_HERSHEY_PLAIN": cv2.FONT_HERSHEY_PLAIN,
    "FONT_HERSHEY_DUPLEX": cv2.FONT_HERSHEY_DUPLEX,
    "FONT_HERSHEY_COMPLEX": cv2.FONT_HERSHEY_COMPLEX,
    "FONT_HERSHEY_TRIPLEX": cv2.FONT_HERSHEY_TRIPLEX,
    "FONT_HERSHEY_COMPLEX_SMALL": cv2.FONT_HERSHEY_COMPLEX_SMALL,
    "FONT_HERSHEY_SCRIPT_SIMPLEX": cv2.FONT_HERSHEY_SCRIPT_SIMPLEX,
    "FONT_HERSHEY_SCRIPT_COMPLEX": cv2.FONT_HERSHEY_SCRIPT_COMPLEX,
    "FONT_ITALIC": cv2.FONT_ITALIC,

    "FILLED": cv2.FILLED,
    "LINE_4": cv2.LINE_4,
    "LINE_8": cv2.LINE_8,
    "LINE_AA": cv2.LINE_AA,
}