---

# describe the data
data:
  title: "Crowd Density %"
  min_value: 0
  max_value: 100
  columns:
    - Minute
    - Sensor_value


# configure the output video
video:
  frame_rate: 30
  resolution: 1080p
  proportions:
    height:
      events_box: 0.12
      background: 0.70
      colourmap: 0.18
    width:
      background: 0.5
      cameras: 0.25  # x2 for LHS & RHS
      colourmap: 0.42
      timer: 0.08


# drawing defaults
drawing:
  output_file_path: "./area_details_file.json"

# heatmap defaults
heatmap:
  output_file_path: "./video.mp4"
