---

# describe the data
data:
  title: "Crowd Density"
  min_value: 0
  max_value: 100


# configure the output video
video:
  frame_rate: 30
  resolution: 1080p
  proportions:
    height:
      events_box: 0.12
      background: 0.70
      colourmap: 0.18
    width:
      background: 0.5
      cameras: 0.25  # x2 for LHS & RHS
      colourmap: 0.42
      timer: 0.08


# drawing defaults
drawing:
  output_file_name: "./area_details_file.json"

default_csv_folder: data/density_csvs
default_video_folder: data/cctv_videos
default_background_folder: data/floor_plans
default_background_image: data/floor_plans/level_5.png
default_output_file: video.mp4
default_area_details_folder: data/area_outlines
default_events_file: data/event_details/level_5.txt
# TODO: remove base_width
default_base_width: 2048
# TODO: remove below once automate colourmap creation
default_colourmap_image: data/colourmap_image.png
default_colourmap_name: plasma
