---

default_csv_folder: data/density_csvs
default_video_folder: data/cctv_videos
default_background_folder: data/floor_plans
default_background_image: data/floor_plans/level_5.png
default_output_file: video.mp4
default_area_details_folder: data/area_outlines
default_events_file: data/event_details/level_5.txt
# TODO: remove base_width
default_base_width: 2048
# TODO: remove below once automate colourmap creation
default_colourmap_image: data/colourmap_image.png
default_colourmap_name: plasma
