---

# describe the data
data:
  title: "Crowd Density %"
  min_value: 0
  max_value: 100
  columns:
    - Minute
    - Sensor_value


# configure the output video
video:
  frame_rate: 30
  resolution: 1080p
  proportions:
    height:
      events_box: 0.15
      background: 0.65
      colourmap: 0.20
    width:
      background: 0.56
      cameras: 0.22  # x2 for LHS & RHS
      colourmap: 0.45
      timer: 0.11


# drawing defaults
drawing:
  output_file_path: "./area_details_file.json"

# heatmap defaults
heatmap:
  output_file_path: "./video.mp4"
