---

# configure components
borders:
  areas:
    colour: [1, 1, 1]  # anything except [0, 0, 0]
  cameras:
    colour: [0, 0, 0]
    type: BORDER_CONSTANT
    width_proportion: 0.02
  event_box:
    colour: [0, 0, 0]
    type: BORDER_CONSTANT
    width_proportion: 0.01
  timer:
    colour: [0, 0, 0]
    type: BORDER_CONSTANT
    width_proportion: 0.03

fonts:
  areas:
    colour: [0, 0, 0]
    type: FONT_HERSHEY_SIMPLEX
    line_type: LINE_AA
    proportions:
      size: 0.0013
      thickness: 0.002
  cameras:  # text on video if video ends
    colour: [1, 1, 1]
    type: FONT_HERSHEY_SIMPLEX
    line_type: LINE_AA
    proportions:
      size: 0.005
      thickness: 0.02
  event_box:
    colour: [0, 0, 0]
    type: FONT_HERSHEY_SIMPLEX
    line_type: LINE_AA
    proportions:
      size: 0.002
      thickness: 0.01
  timer:
    colour: [0, 0, 0]
    type: FONT_HERSHEY_PLAIN
    line_type: LINE_AA
    proportions:
      size: 0.013
      thickness: 0.02


# configurate arrows from cameras to areas
arrows:
  colour: [0, 0, 0]
  line_type: 8
  head_angle: 0.78
  proportions:
    thickness: 0.0015
    head_length: 0.01


# configure background areas
background_areas:
  outline_colour: [1, 1, 1]
  outline_thickness: 2
  transparency_alpha: 0.5
  transparency_gamma: 0
  colour_when_nan: [130, 130, 140]
  text_when_nan: "No Data"


# configurate events text box
events_box:
  text_duration: 5


# configurate cameras
cameras:
  colour_when_finished: [130, 130, 140]
  text_when_finished: "No Video"
