---

# configure components
borders:
  background:
    colour: [0, 0, 0]
    type: BORDER_CONSTANT
    width: 1
  bar_plot:
    colour: [0, 0, 0]
    type: BORDER_CONSTANT
    width: 1
  cameras:
    colour: [0, 0, 0]
    type: BORDER_CONSTANT
    width: 1
  event_box:
    colour: [0, 0, 0]
    type: BORDER_CONSTANT
    width: 1
  timer:
    colour: [0, 0, 0]
    type: BORDER_CONSTANT
    width: 1

fonts:
  areas:
    colour: [0, 0, 0]
    size: 1
    thickness: 1
    type: FONT_HERSHEY_SIMPLEX
    line_type: LINE_AA
  cameras:  # text on video if video ends - "No Data"
    colour: [1, 1, 1]
    size: 3
    thickness: 3
    type: FONT_HERSHEY_SIMPLEX
    line_type: LINE_AA
  event_box:
    colour: [0, 0, 0]
    size: 2
    thickness: 1
    type: FONT_HERSHEY_SIMPLEX
    line_type: LINE_AA
  timer:
    colour: [0, 0, 0]
    size: 1
    thickness: 1
    type: FONT_HERSHEY_PLAIN
    line_type: LINE_AA


# configurate arrows from cameras to areas
arrows:
  line_type: 8
  line_thickness: 2
  line_colour: [0, 0, 0]
  points_on_line: 500
  head_angle: 0.78
  head_length: 15


# configure background
background:
  outline_colour: [0, 0, 0]
  outline_thickness: 2
  transparency_alpha: 0.5
  transparency_gamma: 0
  colour_when_nan: [130, 130, 140]


# configurate events text box
events_box:
  text_duration: 5
