---

# configure components
borders:
  areas:
    colour: [1, 1, 1]  # anything except [0, 0, 0]
  bar_plot:
    colour: [0, 0, 0]
    type: BORDER_CONSTANT
    width_proportion: 0.05
  cameras:
    colour: [0, 0, 0]
    type: BORDER_CONSTANT
    width_proportion: 0.05
  event_box:
    colour: [0, 0, 0]
    type: BORDER_CONSTANT
    width_proportion: 0.05
  timer:
    colour: [0, 0, 0]
    type: BORDER_CONSTANT
    width_proportion: 0.05

fonts:
  areas:
    colour: [0, 0, 0]
    type: FONT_HERSHEY_SIMPLEX
    line_type: LINE_AA
    proportions:
      size: 0.05
      thickness: 0.05
  cameras:  # text on video if video ends - "No Data"
    colour: [1, 1, 1]
    type: FONT_HERSHEY_SIMPLEX
    line_type: LINE_AA
    proportions:
      size: 0.15
      thickness: 0.15
  event_box:
    colour: [0, 0, 0]
    type: FONT_HERSHEY_SIMPLEX
    line_type: LINE_AA
    proportions:
      size: 0.1
      thickness: 0.05
  timer:
    colour: [0, 0, 0]
    type: FONT_HERSHEY_PLAIN
    line_type: LINE_AA
    proportions:
      size: 0.05
      thickness: 0.05


# configurate arrows from cameras to areas
arrows:
  line_type: 8
  line_thickness: 2
  line_colour: [0, 0, 0]
  points_on_line: 500
  head_angle: 0.78
  head_length: 15


# configure background
background:
  outline_colour: [0, 0, 0]
  outline_thickness: 2
  transparency_alpha: 0.5
  transparency_gamma: 0
  colour_when_nan: [130, 130, 140]


# configurate events text box
events_box:
  text_duration: 5
